Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  # Max: 7
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Enabled: false
AllCops:
  Exclude:
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
    <% end %>
    - bin/bundle
    - db/migrate/*
    - db/*
  NewCops: enable