version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    volumes:
      - database-dev-vol:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/ror
    ports:
      - "${RAILS_PORT-3000}:${RAILS_PORT-3000}"
    depends_on:
      - database

volumes:
  database-dev-vol:

networks:
  default:
    name: rails-dev-net
    driver: bridge