version: "3.9"
services:
  database-test:
    image: postgres
    env_file:
      - .env.test.local
    environment:
      - POSTGRES_HOST=database-test
      - POSTGRES_DB=rails_learning_test
    ports:
      - "${POSTGRES_PORT-5433}:5432"
    volumes:
      - database-test-vol:/var/lib/postgresql/data
  web-test:
    build: .
    hostname: web-rails
    env_file:
      - .env.test.local
    environment:
      - POSTGRES_HOST=database-test
      - POSTGRES_DB=rails_learning_test
      - RAILS_ENV=test
      - RAILS_PORT=3001
    volumes:
      - ./:/ror
    depends_on:
      - database-test
    command: ["bundle", "exec", "rails", "test"]

volumes:
  database-test-vol:

networks:
  default:
    name: rails-test-net
    driver: bridge